class exception_handling{
public static void main(String[] args)
{

/*int a = 5,b=0,c;
try
{
c=a/b;
}

catch(Exception e)
{ 
System.out.println("exceptin handaled");
System.out.println(e.toString());
System.out.println(e.getMessage());
e.printStackTrace();
}
System.out.println("after");

}
}*/

/*


int a[] = {10,20,30};
try{

System.out.println(a[3]);
}

catch(Exception e)
{
System.out.println("exception"+e);
}
catch(ArrayIndexOutOfBoundException ab)
{
System.out.println("hello");
}

}
}

*/


/*
String S = "charusat";
try{
System.out.println(S.charAt(9));
}
catch(Exception e)
{
System.out.println("exception"+e);
}

}
}*/

String s1=null;
try{
System.out.println(s1.length());
}
catch(Exception e)
{
System.out.println("handaled"+e);
}


/* try
{
int a = 5,b=0,c;
c=a/b;
int a[] = {10,20,30};
System.out.println(a[3]);
String S = "charusat";
System.out.println(S.charAt(9));
String s1=null;
System.out.println(s1.length());

}
catch(ArrayIndexOutOfBoundException e)
{
System.out.println("array");
}
catch(ArrayIndexOutOfBoundException e)
{
System.out.println("String");
}
catch(ArithmaticException e)
{
System.out.println("Arithmetic");
}
catch(NullPointerException e)
{
System.out.println("Null pointer");
}

}
}*/

int a = 5,b=0,c;
c=a/b;

String S = "charusat";
System.out.println(a[3]);

String S = "charusat";
System.out.println(S.charAt(9));

String s1=null;
System.out.println(s1.length());
try
{
try
{}
catch()
{}

try
{}
catch()
{}

try
{}
catch()
{}

try
{}
catch()
{}	

}
